### ISSUE TITLE
regarding ``negate'' function in src/data/common.py

### ISSUE THREAD

**Issue by Teddy-Li** [mnschmit/lm-lexical-inference#1]
Hi! I've been trying to use this model, and I've found that the ``negate'' function applies only to the Sherliic dataloader, and not to the Levy-Holt dataloader; does it mean that the 5 patterns, when applied to the Levy-Holt dataset, are two symmetric pairs of prompts and just one directional prompt? Thanks!

**Comment by mnschmit** [comment]
Hi @Teddy-Li 
Yes, that is correct. For the Levy/Holt dataset, we do not try to negate premise and hypothesis in the handcrafted patterns from MANPAT. So you could indeed say that 4 of the patterns form symmetric pairs, checking rather for equivalence/synonymy. The combination with the 5th pattern might help focus on directional aspects more.

I'm closing this but feel free to reopen if anything remains unclear!
